"""
Contact referral database model.
"""
import uuid
from ..config.database import db


class ReferralLink(db.Model):
    """Referral invite links generated by users to share with potential contacts."""
    __tablename__ = 'referral_links'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    referral_code = db.Column(db.String(64), unique=True, nullable=False)
    is_active = db.Column(db.Boolean, default=True, nullable=False)
    click_count = db.Column(db.Integer, default=0, nullable=False)
    created_at = db.Column(db.DateTime, server_default=db.func.current_timestamp())
    updated_at = db.Column(db.DateTime, server_default=db.func.current_timestamp(),
                           onupdate=db.func.current_timestamp())
    
    # Relationships
    user = db.relationship('User', backref=db.backref('referral_links', lazy=True))
    
    @staticmethod
    def generate_code():
        """Generate a unique referral code."""
        return uuid.uuid4().hex[:12]
    
    def to_dict(self):
        """Convert to dictionary for JSON serialization."""
        return {
            'id': self.id,
            'user_id': self.user_id,
            'referral_code': self.referral_code,
            'is_active': self.is_active,
            'click_count': self.click_count,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }
    
    def __repr__(self):
        return f'<ReferralLink {self.referral_code} by User {self.user_id}>'


class ContactReferral(db.Model):
    """Contact referrals for new user/organization submissions."""
    __tablename__ = 'contact_referrals'
    
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(100), nullable=False)
    last_name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(255), nullable=False)
    phone = db.Column(db.String(50), nullable=True)
    organization_name = db.Column(db.String(255), nullable=True)
    organization_type = db.Column(db.String(100), nullable=True)
    country = db.Column(db.String(100), nullable=True)
    city = db.Column(db.String(100), nullable=True)
    province = db.Column(db.String(100), nullable=True)
    role_in_organization = db.Column(db.String(100), nullable=True)
    notes = db.Column(db.Text, nullable=True)
    status = db.Column(db.Enum('pending', 'approved', 'rejected'), nullable=False, default='pending')
    parent_referral_id = db.Column(db.Integer, db.ForeignKey('contact_referrals.id'), nullable=True)
    submitted_by_user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    referred_by_link_id = db.Column(db.Integer, db.ForeignKey('referral_links.id'), nullable=True)
    created_at = db.Column(db.DateTime, server_default=db.func.current_timestamp())
    updated_at = db.Column(db.DateTime, server_default=db.func.current_timestamp(),
                           onupdate=db.func.current_timestamp())
    
    # Relationships
    submitted_by = db.relationship('User', backref=db.backref('submitted_referrals', lazy=True))
    referred_by_link = db.relationship('ReferralLink', backref=db.backref('referrals', lazy=True))
    sub_referrals = db.relationship('ContactReferral',
                                    backref=db.backref('referred_by', remote_side=[id]),
                                    lazy=True,
                                    cascade='all, delete-orphan')
    
    def to_dict(self):
        """Convert to dictionary for JSON serialization."""
        return {
            'id': self.id,
            'first_name': self.first_name,
            'last_name': self.last_name,
            'email': self.email,
            'phone': self.phone,
            'organization_name': self.organization_name,
            'organization_type': self.organization_type,
            'country': self.country,
            'city': self.city,
            'province': self.province,
            'role_in_organization': self.role_in_organization,
            'notes': self.notes,
            'status': self.status,
            'parent_referral_id': self.parent_referral_id,
            'submitted_by_user_id': self.submitted_by_user_id,
            'referred_by_link_id': self.referred_by_link_id,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
            'sub_referrals': [r.to_dict() for r in self.sub_referrals] if self.sub_referrals else []
        }
    
    def __repr__(self):
        return f'<ContactReferral {self.first_name} {self.last_name} - {self.email}>'
